# Generated by Django 3.2.7 on 2021-09-09 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionmodel',
            options={'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
        migrations.AlterModelOptions(
            name='rolemodel',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
