# Generated by Django 3.2.7 on 2021-09-11 02:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210909_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='create_time',
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='permissions',
            field=models.ManyToManyField(to='users.PermissionModel', verbose_name='拥有的权限'),
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='菜单名称')),
                ('menu_type', models.IntegerField(choices=[(1, '一级菜单'), (2, '二级菜单'), (3, '三级菜单')], verbose_name='类目级别')),
                ('code', models.CharField(default='#', max_length=64, verbose_name='菜单对应组件路径')),
                ('icon', models.CharField(blank=True, max_length=128, null=True, verbose_name='icon样式')),
                ('curl', models.CharField(default='#', max_length=101, verbose_name='菜单URL')),
                ('hidden', models.BooleanField(default=False, verbose_name='菜单是否隐藏')),
                ('redirect', models.CharField(default='#', max_length=101, verbose_name='菜单跳转url')),
                ('active_menu', models.CharField(default='#', max_length=101, verbose_name='指定高亮')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.menumodel', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='menu',
            field=models.ManyToManyField(to='users.MenuModel', verbose_name='拥有的菜单'),
        ),
    ]
