# Generated by Django 3.2.7 on 2021-09-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210911_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='menu',
            field=models.ManyToManyField(related_name='roles', to='users.MenuModel', verbose_name='拥有的菜单'),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', to='users.PermissionModel', verbose_name='拥有的权限'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(related_name='users', to='users.RoleModel', verbose_name='拥有的所有角色'),
        ),
    ]
